### ISSUE TITLE
paper experiment FHP_DREAM.py cannot run

### ISSUE THREAD

**Issue by zj00377** [EricSteinberger/DREAM#1]
> Traceback (most recent call last):
>   File "FHP_DREAM.py", line 31, in <module>
>     ctrl.run()
>   File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/driver/Driver.py", line 106, in run
>     iter_times = self.algo.run_one_iter_alternating_update(cfr_iter=self._iteration)
> .......
>   File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
>     self.norm_type, self.scale_grad_by_freq, self.sparse)
>   File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> IndexError: index out of range in self
> 

I would like to know why I can't run the paper experiment FHP_DREAM.py, is this a pytorch version issue?

Thanks,
Joena

**Comment by EricSteinberger** [comment]
Hi Joena!

Thank you for opening the issue. I'd need some more info to identify the cause.

1. OS?
2. Did you install all versions and packages as in requirements.txt?
3. Did you try python 3.7? I don't think it's Py3.6's fault, but I used 3.7, so for reproducibility, we should probably stick to that.
4. Could you post the full error rather than just the snippet with "......" in the middle?

Cheers,
Eric

**Comment by zj00377** [comment]
Hi Eric, 

Thanks for the quick response. My system is Ubuntu 16.04. I have installed all versions and packages in requirements.txt. And I use python=3.6, and I don't think it's python version's fault either. I am here to copy the whole error. 

Traceback (most recent call last):
  File "FHP_DREAM.py", line 31, in <module>
    ctrl.run()
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/driver/Driver.py", line 106, in run
    iter_times = self.algo.run_one_iter_alternating_update(cfr_iter=self._iteration)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/driver/_HighLevelAlgo.py", line 52, in run_on
e_iter_alternating_update
    p_id=p_learning, cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/driver/_HighLevelAlgo.py", line 184, in _gene
rate_traversals
    for la in self._la_handles
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/PokerRL/rl/MaybeRay.py", line 49, in get
    return ray.get(obj)
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IndexError): ray::LearnerActor.generate_data() (pid=7777, ip=10.180.0.2)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/local.py", line 161, in generate_data
    cfr_iter=cfr_iter,
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler
.py", line 52, in generate
    super().generate(n_traversals, traverser, iteration_strats, cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line
 23, in generate
    self._traverse_once(traverser=traverser, iteration_strats=iteration_strats, cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line
 42, in _traverse_once
    cfr_iter=cfr_iter,
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line
 58, in _recursive_traversal
    cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler
.py", line 111, in _traverser_act
    sample_reach=sample_reach * sample_strat[a] * n_legal_actions
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line 66, in _recursive_traversal
    cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler.py", line 223, in _any_non_traverser_act
    sample_reach=sample_reach
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line 66, in _recursive_traversal
    cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler.py", line 223, in _any_non_traverser_act
    sample_reach=sample_reach
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/_SamplerBase.py", line 58, in _recursive_traversal
    cfr_iter=cfr_iter)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler.py", line 125, in _traverser_act
    sample_strat=sample_strat,
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineSampler.py", line 267, in _get_utility
    to_np=False,
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/LearnedBaselineLearner.py", line 36, in get_b
    q = self._net(pub_obses=pub_obses, range_idxs=range_idxs, legal_action_masks=masks)
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/PokerRL/rl/neural/DuelingQNet.py", line 29, in forward
    shared_out = self._mpm(pub_obses=pub_obses, range_idxs=range_idxs)
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/MainPokerModuleFLAT_Ba
seline.py", line 97, in forward
    range_idxs_0))
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in 
__call__
    result = self.forward(*input, **kwargs)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/PokerRL/rl/neural/CardEmbedding.py", line 68, in forward
    card_o.append(emb(ranks=ranks, suits=suits, cards=cards))
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in 
__call__
    result = self.forward(*input, **kwargs)
  File "/home/zj00377/fpoker/Deep-CFR/DREAM/PokerRL/rl/neural/CardEmbedding.py", line 99, in forward
    embs += self.card(c) * valid_c + self.suit(s) * valid_s
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in 
__call__
    result = self.forward(*input, **kwargs)
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in 
forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/zj00377/anaconda3/envs/deepcfr/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in emb
edding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by zj00377** [comment]
Here is the value of input and weight of function torch.embedding, when the program break.

` (pid=17941) input tensor([2]) embedding torch.Size([13, 64])
(pid=17941) input tensor([4]) embedding torch.Size([52, 64])
(pid=17941) input tensor([6]) embedding torch.Size([4, 64])`

It seems like the suits are not calculated properly? But I'm not quite sure about it.

**Comment by EricSteinberger** [comment]
How many cores does the machine you are running on have? Could you also post the full output all the way from the first console line printed rather than just the error?

I just tried to reproduce this with the recommended AWS setup and it all worked

**Comment by zj00377** [comment]
I used Google Cloud Compute Engine. 
Here is my machine information:

>  Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> Address sizes:       46 bits physical, 48 bits virtual
> CPU(s):              16
> On-line CPU(s) list: 0-15
> Thread(s) per core:  2
> Core(s) per socket:  8
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               85
> Model name:          Intel(R) Xeon(R) CPU @ 2.00GHz
> Stepping:            3
> CPU MHz:             2000.144
> BogoMIPS:            4000.28
> Hypervisor vendor:   KVM
> Virtualization type: full
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            1024K
> L3 cache:            39424K
> NUMA node0 CPU(s):   0-15

I have also attached
[full_error_track.txt](https://github.com/EricSteinberger/DREAM/files/4841029/full_error_track.txt)
 the full output from the first console line printed in the attach file.

**Comment by EricSteinberger** [comment]
Thank you! Could you try one with at least 32 CPUs and 100GB RAM? Does the Leduc experiment work?

**Comment by zj00377** [comment]
The Leduc experiments work, but all flopHoldem do not work.

Dose the CardEmbedding.py matter with CPU and RAM? Is there a way to lower down the CPU and RAM requirements?

**Comment by EricSteinberger** [comment]
The machine should be crashing at 16 CPUs because the parameter set for the number of workers in the experiment you are running requires more CPUs to launch. I don't understand why the Embedding error comes up, but it might be a side effect of processor sharing.

You can decrease this by reducing the number of "LearnerActor" workers and the number of "RLBR" workers used. The experiments for the paper took 1 week with the current number of workers, so we don't recommend lowering it.

For the purpose of testing, please just launch a machine with more cores. AWS machines are relatively affordable and run them very fast. I recommend using the "c5.9xlarge" machine for single FHP runs and "c5.24xlarge" if you run 3 runs on the same machine

**Comment by zj00377** [comment]
Thanks for the recommendation. 

I am currently only using 1 worker for training and 1 worker for RLBR for testing. I also reduce all related parameters by divide 12. But the embedding error still came up, is that means simply reduce the parameters may not work as well?

**Comment by EricSteinberger** [comment]
Thank you! Alright, seems like it's not that then. Which parameters did you divide by 12?

I tested the exact script out of the box with the recommended setup and it works. So, it's probably one of the things that's different between your setup and mine that causes it. From what you've reported so far, reasons I can see are:
- GCP (never ran on that)
- PyTorch version (but should be good if you follow the requirements.txt)
- Some hyperparameter change that shouldn't happen (most likely at the moment from my perspective; sorry if you are sure it's not that!)

For the purpose of reproduction, could you run the exact script as provided in the repo on a machine with enough cores and RAM on GCP? If this works, change things step by step to what you have now and see where it breaks - solved!

If it doesn't work, then it's either GCP or that my setup and predefined AWS image have something on it that the current requirements.txt and instructions don't ask you to install. To test the former, I ran this on AWS and it worked. I also never got this report for my other libraries which use the same core framework (but different PyTorch versions). But if you get to this point, I'm happy to investigate more deeply into the cause.

**Comment by zj00377** [comment]
Thanks for all these suggestions and possible reasons. I gonna use exact same settings as the repo and the same AWS machine to try it out.

**Comment by zj00377** [comment]
Hi Eric, 

I can run the experiment now with Flop3Holdem, Flop5Holdem. :) However, if I change the game to LimitHoldem, the same error occurs.....I check out the code, I can't find too mang differences of game/game_rule between Flop5Holdem and LimitHoldem. Could you also try out LimitHoldem to see whether you also meet the same error? Thanks a lot.

Joena

**Comment by EricSteinberger** [comment]
Hi! That's great news! You're right, there isn't that much of a difference between the games, other than the depth of the tree. However, for LimitHold'em, you'll probably need even more RAM. A good thing to test first is always "does a bigger machine fix it?" The two ways of testing this are

1. reducing the number of workers and reducing the size of the buffers
2. using a bigger machine

If a machine with 200GB RAM or more doesn't cut it given the settings as given in the starting script but changing the game to Limit Holdem, let me know. I didn't run DREAM in Limit Hold'em actually, but I did run Deep CFR in it and the two are similar in terms of computational requirements. I'll make sure to look into it if scaling the algo down or the machine up doesn't work for you.

**Comment by EricSteinberger** [comment]
closing due to inactivity and not able to reproduce
